version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres.dev
    container_name: auth_postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - DB_NAMESPACE=auth
volumes:
  postgres_data:
